---
title: "About HPAM 7660"
---

### Course Description

HPAM 7660 - Health Policy Analysis presents an overview of health policy in the United States – its scope, its dynamics, and its conceptual and practical dilemmas. The course is designed to acquaint students with major issues in the policymaking process, specifically in formulating, implementing, and assessing those patterns of government decision. Students will explore the history and structure of the American health care system, as well as explore a policy issue of their choosing using the Bardach analytical method.


### Student Learning Objectives

1. Exhibit a conceptual understanding of the forces and factors accounting for legislation and regulation pertaining to health services.\
2. Develop a framework to critically discuss and evaluate policy issues affecting the U.S. health care system.\
3. Compare and contrast the public policy objectives of various stakeholders with the realities of the political process.\
4. Critically evaluate the research literature that examines the federal and state roles in health services.\
5. Evaluate current proposals advanced in Congress and by the private sector that impact health services delivery.\
6. Demonstrate a working understanding of the legislative process and the related federal and state regulation processes.\