---
title: "Syllabus"
slug: syllabus
summary: "Information about the content and policies for HPAM 7660"
citeproc: true
output:
  blogdown::html_page:
      toc: TRUE
---




::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}
### Instructor

- {{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>

:::

::: {.g-col-6}
### Course Details

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}

:::

### Office Hours

- {{< fa calendar >}} &nbsp; {{< var instructor.office_days >}}
- {{< fa clock >}} &nbsp; {{< var instructor.office_time >}}
- {{< fa university >}} &nbsp; {{< var instructor.office_loc >}}

:::


### Course Descripton

HPAM 7660 presents an overview of health policy in the United States – its scope, its dynamics, and its conceptual and practical dilemmas. The course is designed to acquaint students with major issues in the policymaking process, specifically in formulating, implementing, and assessing those patterns of government decision. Students will explore the history and structure of the American health care system, as well as explore a policy issue of their choosing using the Bardach analytical method.

### Course Readings

We will use the following online (and free!) textbook along with various readings that will be posted to the course website under the Assignments tab.

- Ismay, Chester and Albert Y. Kim. 2022. [*Statistical Inference via Data Science: A ModernDive into R and the Tidyverse*](https://moderndive.com/index.html). 

### Course Evaluation

The following components and weights will be used to calculate your final grade:

| Category      | Percent of Final Grade |
|:-------------------|:-------------------|
| Class participation   | 10%                    |
| Reading Discussion Questions & Problem Sets  | 40%                    |
| Policy Memo         | 30%                    |
| Case Presentation | 20%                    |
| Peer Assessment | 25% |


*Policy Memo* - throughout the semester, you will construct a policy memo to be submitted on the final day of class. The memo should advocate for a policy position of your choice and can be targeted to local leaders (e.g., mayor, city council, etc.), or state or federal legislators. The target audience will depend on the scope of your policy. The final draft of the policy memo should be approximately 8-10 pages, excluding references.

The University of Southern California library provides a good [guide](https://libguides.usc.edu/writingguide/assignments/policymemo) for writing a policy memo. Note that as the guide states: “You should not approach writing a policy memo in the same way as you would an academic research paper. Yes, there are certain commonalities in how the content is presented [e.g., a well-written problem statement], but the overarching objective of a policy memo is not to discover or create new knowledge. It is focused on providing a pre-determined group of readers the rationale for choosing a particular policy alternative or specific course of action. In this sense, most policy memos possess a component of advocacy and advice intended to promote evidence-based dialog about an issue.”
Your policy memo will consist of the following 7 sections, that will be submitted individually throughout the semester before a final version of the memo to be submitted on the last day of class:

1.	Executive summary\
2.	Introduction and problem definition (Bardach Step 1)\
3.	Issue analysis (Bardach Step 2)\
4.	Proposed solutions (Bardach Steps 3, 4, & 5)\  
5.	Strategic recommendations (Bardach Step 6 & Step 7)\
6.	Conclusion (Bardach Step 8)\
7.	References\

Policy Memo Due Dates:

1.	Problem statement – Feb. 28th\ 
2.	Preliminary reference list – March 14th\  
3.	Introduction and problem definition draft – March 21st\  
4.	Issue analysis draft – March 28th\
5.	Proposed solutions draft – April 11th\   
6.	Strategic recommendations draft – April 25th\ 
7.	Executive summary and conclusions draft – May 2nd\  
8.	Final draft & Infographic – May 9th\ 

*Case Presentation* - The case presentation will take place on May 2nd. The case presentation will coincide with a series of panel discussion during our “virtual D.C. experience”. I’ll provide more detail on the schedule and content of these panels on the course website along with a rubric for the case presentations.

*Reading Discussion Questions & Problem Sets* – Reading discussion questions will be due by class time each Tuesday afternoon and should be submitted through Canvas. I will post the reading discussion questions to Canvas at least a week in advance of the due date.  

*Peer Assessment* - The peer assessment component of your grade will consist of anonymous grading of your team contribution by the other members of your team (more specific details to follow).

Your final course grade will be calculated according to the following ranges:

| Letter Grade      | Percentage |
|:-----------|:---------------------------|
| A  | 94% and above                    |
| A- | 90 to 93.9%                    |
| B+ | 85 to 89.9%                |
| B  | 80 to 84.9%                    |
| B- | 75 to 79.9% |
| C  | 70 to 74.9% |
| F  | <70% |

### Late Policy

Late submissions will be given half credit.

### SPHTM Honor Code

I expect that you will abide by the school’s Honor Code and Code of Academic Conduct. Failure to do so will result in referral to the Honor Board. I encourage you to discuss the lectures and coursework with your colleagues to facilitate your understanding of the material. But I expect that you will engage in independent scholarship when completing your own work, properly citing external assistance or sources. If you have any questions about these expectations, please refer to the code or ask me in advance. 

### Americans with Disabilities Act of 1990

It is the policy and practice of Tulane University to comply with the Americans with Disabilities Act (Pub. L. No. 101-336), Section 504 of the Rehabilitation Act of 1973 (Pub. L. No. 93-112, §504, as amended), and state and local requirements regarding individuals with disabilities. Under these laws, no qualified individual with a disability shall be denied access to or participation in services, programs, and activities of Tulane University. Students seeking academic adjustments or accommodations must register their disabilities with the [Goldman Center for Student Accessibility](https://accessibility.tulane.edu/). 

### Title IX

Tulane University recognizes the inherent dignity of all individuals and promotes respect for all people. As such, Tulane is committed to providing an environment free of all forms of discrimination including sexual and gender-based discrimination, harassment, and violence like sexual assault, intimate partner violence, and stalking. If you (or someone you know) has experienced or is experiencing these types of behaviors, know that you are not alone. Resources and support are available: you can learn more [here](https://allin.tulane.edu/content/all). Any and all of your communications on these matters will be treated as either “Confidential” or “Private” as explained in the chart below. Please know that if you choose to confide in me I am mandated by the university to report to the Title IX Coordinator, as Tulane and I want to be sure you are connected with all the support the university can offer. You do not need to respond to outreach from the university if you do not want to.

| Confidential     | Private |
|:-------------------|:-------------------|
| Except in extreme circumstances, involving imminent danger to one’s self or others, nothing will be share without your explicit permission.  | Conversations are kept as confidential as possible, but information is shared with key staff members so the University can offer resources and accommodations and take action if necessary for safety reasons.                    |
| Counseling & Psychological Services (CAPS):<br> (504) 314-2277 | Case Management & Victim Support Services (CMVSS): (504) 314-2160  |
| Student Health Center<br> Downtown: (504) 988-6929<br> Uptown: (504) 865-5255 | Tulane University Police (TUPD)<br> Downtown: (504) 988-5531<br> Uptown: (504) 865-5911   |
| Sexual Aggression Peer Hotline and Education (SAPHE): (504) 654-9543 | Title IX Coordinator: (504) 865-5611 or\ email: titleix@tulane.edu    |

### Student Learning Objectives

1.	Exhibit a conceptual understanding of the forces and factors accounting for legislation and regulation pertaining to health services.\
2.	Develop a framework to critically discuss and evaluate policy issues affecting the U.S. health care system.\
3.	Compare and contrast the public policy objectives of various stakeholders with the realities of the political process.\
4.	Critically evaluate the research literature that examines the federal and state roles in health services.\
5.	Evaluate current proposals advanced in Congress and by the private sector that impact health services delivery.\
6.	Demonstrate a working understanding of the legislative process and the related federal and state regulation processes.\

### Course Competencies

The Department of Health Policy & Management has adopted a set of competencies for evaluating each of our masters-level programs, including both the MPH in Health Policy and the MHA. Our accrediting bodies ask that we demonstrate, on a course level, which program competencies are supported and developed through this particular course. Some competencies are given more attention in the course activities and materials. The subsections below indicate to what extent each competency is addressed in the course materials, activities, and evaluation process.

**MPH in Health Policy Program Competencies**

| Competency  | Degree Covered |  Learning Objectives |
|:----------------|:--------|:------------|
Analyze the influence of policy mechanisms on patient and provider behavior and health systems outcomes. | P | 1,3,5,6,7 |
Assess health systems performance and issues of quality, access, and efficiency. | R | 1,2,3,5,6,7 |
Critique health policy literature. | R | 4 |
Communicate health policy issues written and orally. | P | 2,3,4 |

**MHA Program Competencies**

| Competency  | Degree Covered |  Learning Objectives |
|:----------------|:--------|:------------|
Speak and write in a clear, concise, and logical manner in formal and informal situations within health care settings to convey cogent business presentations and to facilitate a group. (Effective Communication) | R | 2,4 |
Consider the business, demographic, ethno-cultural, political, and regulatory factors in developing strategies that continually improve the long-term success and viability of health care organizations. (Strategic Management) | R | 1,3,5 |
Deconstruct complex problems into smaller elements and synthesize that with other data to derive recommendations. (Critical Thinking and Analysis) | P | 6,7 |
<font size= "3"> Rating Scale for Degree of Coverage: P = primary, R = reinforcing <font size= "5"> <br> 

**Competency Map**

| Learning Objective  | Program Competency |  Learning Activity | Primary Assessment
|:--------------|:------------|:-------|:-------|
Exhibit a conceptual understanding of the forces and factors accounting for legislation and regulation pertaining to health services. | MPH in HP – Competency 1 <br> MHA – Strategic Management | Lectures | Exams |
Develop a framework to critically discuss and evaluate whether the “market” in health services is or is not a policy issue. | MPH in HP – Competency 1 | Lectures <br> Group Presentations | Exams |
Compare and contrast the public policy objectives of Medicare, Medicaid, and the private insurance sector with the realities of the political process. | MPH in HP – Competency 2 <br> MHA – Critical Thinking | Lectures <br> Group Presentations | Exams <br> Policy Memo |
Critically evaluate the research literature that examines the federal and state roles in health services. | MPH in HP – Competency 3 | Writing Workshops | Policy Memo |
Evaluate current proposals advanced in Congress and by the private sector that impact health services delivery. | MPH in HP – Competency 1 <br> MHA – Strategic Management | Group Presentations | Exams |
Demonstrate a working understanding of private insurance and the federal and state regulation that oversees it. | MPH in HP – Competency 1 <br> MHA – Strategic Management | Lectures | Exams |
Examine the development and regulation of the private insurance market over the past 20 years. | MPH in HP – Competency 1 | Lectures | Exams |








### Expectations

In this course, you will be expected to

- complete eight problem sets,
- complete eight weekly tutorials,
- take two take-home, open-book exams, and
- write one final data analysis project.


### Prerequisites

No prerequisites will be assumed.  If you are unfamiliar with downloading and installing software programs on your Mac or PC, you may want to allocate additional time to make sure those aspects of the course go smoothly. In particular, we have developed a [Problem Set 0][ps0] to guide you through installing R, RStudio, and git to give you a sense of the tools we will be using.

### Credit

This course satisfies the Methods requirement for the Government department and the [Quantitative Reasoning with Data](https://qrd.college.harvard.edu) requirement in the Harvard College Curriculum. It also counts toward completion of the Government department [Data Science track](https://www.gov.harvard.edu/undergraduate/programs-of-study/data-science/). 

### Speaker Series

On various Fridays throughout the semester, we will host the [Gov 50 Speaker Series](/resources/speaker-series.html), where guest speakers working in data science in various industries will discuss their career paths and answer student questions. 


## Course structure

### Flow of the Course

The course will follow a basic flow each week, with small differences if a tutorial or problem set is due or not. 

- **Monday**: Complete reading/watching course material, complete tutorial (if due). 
- **Tuesday**: Lecture meets. 
- **Wednesday**: Submit problem set by 11:55 PM (if due). 
- **Thursday**: Lecture meets; problem sets and exams posted; sections meet.
- **Friday**: Sections meet. 
- **Sunday**: Submit exams by 11:55 PM (if due)

### Tutorials

We will assign short weekly tutorials to assess your knowledge of the material covered in the reading/video materials that week. While you are expected to complete them on time, they will be graded based on completion not on how correct the answers are. With some exceptions, they will usually be due Mondays at 11:59pm ET. 

### Lectures

We will meet twice a week for lectures where I will combine presenting material and doing live coding demonstrations. Ideally, you should bring your laptop to class and be ready to code along with me! We will have a Slack channel dedicated to answer computing questions by TFs during lecture. Lectures will be recorded and usually posted to Canvas within 24 hours of the lecture time. Keeping up with these lectures is vital to your success in the class. 


### Sections

Sections will be small-group settings to practice the tools and techniques that we cover in class. These meetings are *essential* to gaining the skills you need for the problem sets, exams, and final project. You are **expected** to attend sections. We will not assign you a particular section, so you are free to attend one that works for your schedule and attend different sections throughout the semester if a conflict arises. 

Sections will fall into two types based on prior exposure to the course material: more comfortable and less comfortable. While Gov 50 is designed to be accessible to students without prior exposure to data science and computing, we recognize that students with different backgrounds in the material may require different pedagogical approaches. 


### Study Halls

Study halls are a combination of office hours and drop-in tutoring sessions. Course assistants will hold a table usually at one of the house dining halls or common rooms and help students with assignments and course material. Study halls work best if you come as a group and work on the assignments on your own while you are there and ask for help from the CAs when you get stuck. 

You can find a list of the Study Hall times on the [Study Hall Schedule](/resources/study-halls.html) page. 


### Problem Sets

Only reading about data science is about as instructive as reading a lot about hammers or watching someone else wield a hammer. You need to get your hands on a hammer or two. Thus, in this course, you will have mostly-weekly problem sets that will give you an opportunity to apply the statistical techniques you are learning. They will usually be focused on data analysis in general and will often involve a real dataset. 

We encourage students to rely on peer working groups as they work on these homeworks, but each student will submit their own work individually. We will facilitate the formation of homework peer groups.

:::{.callout-note}
## Grace policy

When calculating the final homework portion of the overall grade, we will drop the lowest score and use the remaining scores. Thus, if you have an emergency that forces you to miss one homework, your grade will not be severely affected.

:::


### Exams

There will be two take-home exams during the course. This exam will be similar to a homework in format and in the sense that it will be open book and open internet, but you will not be allowed to collaborate with other students or be able to communicate with any humans about the exam. You will be given several days to complete the exam. We will provide more information about the exam as it approaches. 

| Exam   | Release Date            | Due Date                 |
|:-------|:------------------------|:-------------------------|
| Exam 1 | Thu, Oct 19th 5:00pm ET | Sun, Oct 22nd 11:59pm ET |
| Exam 2 | Thu, Dec 7th 5:00pm ET | Sun, Dec 10th 11:59pm ET |
 
### Discussion

We will be using the [Ed platform]() for discussions on course material. There is a [users guide](https://us.edstem.org/quickstart/ed-discussion.pdf) to help orient yourself to the platform. We will enroll you into the platform toward the start of the semester. 


### Grading

You (the student) and I (the instructor) should care the most about what you *learn*, not what numerical/letter summary of that learning you get at the end of the semester. So I would love to not have grades at all, but unfortunately we humans are very good at procrastinating on our good intentions when there is no incentive not to. Thus, we have grades to help solve this commitment problem and to encourage you to put effort into learning the course material. 

Here are how each portion of course contributes to the overall grade:

| Category      | Percent of Final Grade |
|:--------------|:-----------------------|
| R Tutorials   | 10%                    |
| Problem Sets  | 40%                    |
| Exams         | 30%                    |
| Final Project | 20%                    |


We will use [Gradescope](https://www.gradescope.com/) for submission of the various assignments throughout the semester. Once enrollment is finished, Gradescope will automatically connect through Canvas. 


**Bump-up policy**: We reserve the right to "bump up" the grades of students who have made valuable contributions to the course in the lecture, sections, study halls, or discussion/Slack. This also applies to students who show tremendous progress and growth over the semester. 






## Final Project



The final project is a data analysis project about whatever data excites you. That could be public opinion in U.S. elections, United Nations voting patterns, patterns of racial discrimination in police behavior, the distribution of salaries in basketball, or the economics of the Marvel Cinematic Universe. No matter the topic, you will formula a key research question, find data on that question, answer the question using the tools of the course, and present those results for public consumption. 

The goal is for this to be a *professional* project that you can use to showcase the skills that you have gained to potential employers. Your final submission will be a publicly available article/website that contains: (1) a brief introduction to the research question and data collected; (2) a visualization of the data in question that speaks to your research question; (3) a presentation (as a table or graph) of a regression model assessing your question along with a plain-English interpretation; (4) a brief (one-paragraph) section that describes limitations of your analysis and threats to inference, and states how your analysis could be improved (e.g., improved data that would be useful to collect). Finally, there must be a link to the GitHub repo that contains the source code to load, clean, and analyze the data and produce the article. 

The data collection and cleaning must be meaningful---it's not sufficient to simply use a pre-cleaned data from an R package. Self-collected data is allowed and even encouraged, though beware that it can only be used for the final project itself only unless you go through [human subjects approval from the University](https://cuhs.harvard.edu/undergraduate-research-and-course-projects).  


| Milestone                    | Due Date                 |
|:-----------------------------|:-------------------------|
| Creating a GitHub Repository | Fri, Sep 29th 11:59pm ET |
| Data and Proposal            | Fri, Oct 13th 11:59pm ET |
| First Visualization          | Fri, Nov 3rd 11:59pm ET  |
| First Analysis               | Fri, Nov 17th 11:59pm ET |
| Final Report                 | Wed, Dec 13th 11:59pm ET |





## Course Policies

### Late Policy

For problem sets, late submissions will be penalized 10% if submitted 0-24 hours late and penalized 20% if submitted 24-48 hours late. We will not accept any submissions after 48 hours. This penalty will be waived the **first time** a submission is late. 


### Regrading Policy

If you feel there has been an error in the grading of one your assignment, you may request (in writing) a regrade of the assignment. Please send your request in an email to Professor Blackwell and the Head TF. A member of the teaching staff will regrade the entire assignment, not just the part you are disputing. Therefore, your regrade might increase or decrease the overall grade on the assignment. 


### Office Hours and Availability

Office hours for the teaching staff are listed on the [Office Hours Schedule](/resources/office-hours.html) page. 

If you have a general question, you should post it to the Ed discussion board (where you can make your question anonymous if you would like). This is almost always the fastest way to get an answer. However, you can also email me directly at [mblackwell@gov.harvard.edu](mailto:mblackwell@gov.harvard.edu) if you have a question that is about a personal situation. 

### Academic Honesty

The work that you do in both the problem sets should be your own work. You may seek help from others so long as this does not result in someone else completing your work for you. When asking for help, you may show others your code to help diagnose a bug or highlight a potential issue, but you should not view their (working) code. You should cite any discussions you have with other students in your problem set and note if they helped you with your code. You should never copy and paste code from another student or elsewhere (e.g., websites, former students). 

I also strongly suggest that you make a solo effort at all the problems before consulting others. The exams will be very difficult if you have no experience working on your own. **There is no collaboration allowed on the exams.**


## Course materials

###  Books
We will use the following books in this class:

- Imai, Kosuke and Nora Webb Willaims. 2022. [*Quantitative Social Science: An Introduction with Tidyverse*](https://press.princeton.edu/books/paperback/9780691222288/quantitative-social-science), 2022. Princeton University Press.
- Ismay, Chester and Albert Y. Kim. 2022. [*Statistical Inference via Data Science: A ModernDive into R and the Tidyverse*](https://moderndive.com/index.html). 
- Mine Cetinkaya-Rundel and Johanna Hardin. 2021. [*Introduction to Modern Statistics*](https://www.openintro.org/book/ims/). OpenIntro. 

The following books are optional, but may be helpful to build you understanding of the material:

- Freedman, David, Pisani, Robert, and Purves, Roger. 2007. *Statistics*. W.W. Norton & Company. 4th edition.
- Gonick, Larry, and Woollcott Smith. 1993. *The Cartoon Guide to Statistics*. HarperPerinnial. 


### Computing

We'll use R in this class to conduct data analysis. R is free,  open source, and available on all
major platforms (including Solaris, so no excuses). [RStudio](http://www.rstudio.com) (also free) is a graphical interface to R that is widely used to work with the R language. You can find a virtually endless set of resources for R and RStudio on the internet. For beginners, there are several web-based tutorials. In these, you will be able to learn the basic syntax of R. We'll post more R resources on the course website. We will also use git and Github to manage our projects. 

You can get setup with all of these tools by completing [Problem Set 0][ps0]. 

## Mental Health

College is a stressful time in one's life and mixing it with a global pandemic, remote learning, and dislocation makes this one of the most fraught semester any of us have probably faced. We acknowledge that nothing is quite normal and that there may be times when you feel overwhelmed by this course or by life more generally. Please feel free to reach out to any of the course staff if you want to talk about any issues you are having with the course or anything else. We will always try to help and we are committed to being extra accommodating this semester on course policy issues. Please just get in touch. 

Of course, there are other resources at Harvard if you need them. A few are listed below:

* [Counseling and Mental Health Services](https://camhs.huhs.harvard.edu/)
* [Room 13](https://www.hcs.harvard.edu/~room13/)


[ps0]: assignments/00-problem-set.html

## Accessibility 

Harvard University values inclusive excellence and providing equal educational opportunities for all students. Our goal is to remove barriers for disabled students related to inaccessible elements of instruction or design in this course. If reasonable accommodations are necessary to provide access, please contact the [Disability Access Office (DAO)](https://aeo.fas.harvard.edu/). Accommodations do not alter fundamental requirements of the course and are not retroactive. Students should request accommodations as early as possible, since they may take time to implement. Students should notify DAO at any time during the semester if adjustments to their communicated accommodation plan are needed.
