---
title: "HPAM 7660 Resources"
---

<!-- ## FAH Fellowship Description -->

<!-- - Description [here](/resources/FAH_fellowship.pdf). If you are interested, please email me your resume by Friday, March 15th at noon. -->

## Policy & Advocacy Resources

- [Landscape Analysis Example - Problem Identification](/resources/LPHI-Barriers-Report-Final.pdf)
- [Landscape Analysis Example - Legislative Landscape](/resources/Medicaid_Doula_Landscape.pdf)
- [One-Pager Template](https://everylifefoundation.org/wp-content/uploads/2020/11/RDLA-Tip-Sheet-One-Pagers.pdf)
- [Tips for Creating an Effective One-Pager](https://publichealth.jhu.edu/lerner-center/resources/how-to-create-a-one-pager) \
- [Tips for Creating an Effectice Infographic](https://onlinelibrary.wiley.com/doi/10.1002/aet2.10793) \
- [HPAM 7660 Policy Memo Example](/resources/Policy_Memo_Example.pdf)
- [Tips for Providing Public Testimony](https://laddc.org/lacan/how-to-advocate/getting-started/provide-public-testimony/)
- [Louisiana Senate Video Archive](https://senate.la.gov/Video_Archive) \
- [Louisiana House of Representatives Video Archive](https://house.louisiana.gov/h_video/Hse_Video_OnDemand) \

## Software Installation Guides

- [Getting Software Set Up](/assignments/tutorial_1.qmd)
- [Troubleshooting Guide](/resources/troubleshooting.qmd)

## R Tutorials

- [Hands On Programming with R](https://rstudio-education.github.io/hopr/)
- [R for Data Science](https://r4ds.had.co.nz/)
- [R Programming Cheatsheet](/resources/cheatsheet.qmd)

#### R Markdown

- [R Markdown Tutorial](https://rmarkdown.rstudio.com/lesson-1.html)
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
- [R Markdown Cheatsheet](/resources/rmarkdown-cheatsheet.pdf)

#### Making Tables with R

- [R to LaTeX/Word Guide](/resources/R_tables.qmd)

## STATA Tutuorials

#### Making Tables with STATA

- [STATA to LaTeX/Word Guide](/resources/Stata_tables.qmd)

#### STATA Code Templates

- [Code templates](/resources/Stata_templates.qmd)

## Git and GitHub Tutorials

- [Happy Git with R](https://happygitwithr.com)
- [VS Code and GitHub](/resources/VSCode_Git.qmd)
- [Overleaf and GitHub](/resources/Overleaf_Git.qmd)

## VS Code Tutorials

- [VS Code Installation and Extensions](/resources/VSCode.qmd)

