---
title: "Data Assignment 3 - Data Wrangling, LA Mortality Files"
summary: >-
  Create a Markdown document with R code for importing the LA Mortality data and a description of each variable in the data.
---

### Instructions

In this assignment, you'll write code to import the Louisiana Mortality Files (we already did this in [Tutorial 3](/assignments/tutorial_3.qmd)) and you'll identify each of the variables included in the data. It's important to know what each variable is measuring before we can create an analytic file for analysis. 

Before beginning the assignment, create a GitHub repo called `hpam7660_data3`. Then create a new RStudio project and link it to the new GitHub repo. Once you've done that, open a new Markdown document and give it a YAML header that includes the title "HPAM 7660 Data Assignment 3", your name, the date, and "pdf_document" as the output format.

As you answer each of the following questions, be sure to include your R code and associated output in your Markdown document. Additionally, add a line or two describing what you're doing in each code chunk. 


### Steps for Completing the Assignment

1. Use the `read_csv` command to load the LA Mortality Files into RStudio.

2. Each year of the data has its own associated data documentation on the CDC site. We could go through the documentation file for each year, but it turns out that the data fields don't change much from year to year. So, for our purposes, we can use the 2019 data documentation file to describe the data set. Open the [documentation file](https://www.cdc.gov/nchs/data/dvs/Multiple-Cause-Record-Layout-2019-508.pdf) for the 2019 Mortality Multiple Cause-of-Death Files. Open the data documentation file by following the link above.

3. Each variable in the LA Mortality File has a corresponding entry in the documentation file. For example, the first varable listed when you preview the data frame should be ...

Summarizing data????

Do we want to include any examples from the book here? We could do that first and save the mortality stuff for the end.