---
title: "HPAM 7660 - Week 15 Materials"
subtitle: "Virtual DC Experience"
---

## Tuesday, April 23 Virtual D.C. Experience Schedule

[**Zoom Link**](https://tulane.zoom.us/j/8301248326?omn=96277352599&from=addon)

| Time      | Panelists |
|:-------------------|:-------------------|
12:30pm to 1:15pm   | **Advocacy** <br> - [Lauren Crawford Shaver](https://www.fticonsulting.com/experts/lauren-crawford-shaver), Senior Managing Director, FTI Consulting |
1:15pm to 2:00pm    | **Federal Agencies** <br> - [Jim Matthews](https://www.linkedin.com/in/james-e-mathews-5277aa239/), Principal, Health Policy Alternatives, former MedPAC Advisory Commission Executive Director |
2:00pm to 2:30pm    | Break |
2:30pm to 3:15pm    | **Media** <br> - [Amy Goldstein](https://www.brookings.edu/people/amy-goldstein/), Brookings Institute Visiting Fellow, Washington Post Staff Writer <br> - [Robert King](https://www.politico.com/staff/bob-king), Deputy Editor Politico <br> <ins>*Example reporting*</ins>*:* <br> Goldstein - [Medicaid](/materials/Goldstein_Medicaid.pdf) & [COVID](/materials/Goldstein_COVID.pdf) <br> King - [Medicare Advantage](/materials/King_MA.pdf) & [ACA](/materials/King_Obamacare.pdf)                   |
3:15pm to 4:00pm    | **Think Tanks and Foundations** <br> - [Jim Capretta](https://www.aei.org/profile/james-c-capretta/), Senior Fellow, American Enterprise Institute <br> - [Tricia Neuman](https://www.kff.org/person/tricia-neuman/), Senior Vice President, Executive Director for Program and Medicare Policy and Senior Advisor to the President, Kaiser Family Foundation |
                                

## Thursday, April 25 Virtual D.C. Experience Schedule

[**Zoom Link**](https://tulane.zoom.us/j/8301248326?omn=96446456337&from=addon)

| Time      | Panelists |
|:-------------------|:-------------------|
1:30pm to 2:00pm    | **Federal Agencies** <br> - [Erin Richardson](https://www.cms.gov/about-cms/leadership/chief-of-staff), Chief of Staff, Office of the CMS Administrator |
2:00pm to 2:30pm    | **Legislative Branch** <br> - [Amy Hall](https://www.linkedin.com/in/amy-hall-77314a5/), Staff Director, Subcommittee on Health, U.S. House of Representatives Committee on Ways and Means |
2:30pm to 2:45pm    | Break |
2:45pm to 3:30pm    | **Executive Branch** <br> - [Chris Jennings](https://www.jenningsps.com/about), Jennings Policy Strategies, former Obama Administration Senior Advisor for Health Policy and Coordinator of Health Reform  |
3:30pm to 4:15pm    | **Winston Fellows** <br> - [Katarina Morgan](https://winstonfellowship.org/) <br> - [Ari Panzer](https://winstonfellowship.org/)