---
title: "HPAM 7660 - Week 16 Materials"
subtitle: "Case Study & Case Study Teams"
---

## Tuesday, April 30

**Case Study** 

- [The Road Ahead for Medicare Advantage: Strategies for Sustainable Growth](/materials/HPAM_7660_Sp24_Case_Study.pdf)

**Case Teams**

- Team 1, 12:00pm to 12:30pm: Black, Clements, Zuhaira
- Team 2, 12:30pm to 1:00pm: English, Howland, Johnson, LaBattes
- Team 3, 1:15pm to 1:45pm: Letsinger, Shoemaker, Varady, Waugh
- Team 4, 1:45pm to 2:15pm: Assefa, Cohen, Shah, Shimanovsky
- Team 5, 2:30pm to 3:00pm: Brennan, Lindgren, Schindel
- Team 6, 3:00pm to 3:30pm: Arkfeld, Pachpor, Shiferaw, Toole

**Case Judges**

- [Jennifer Friedman](https://fhpstrategies.com/our-team/jennifer-friedman), Senior Vice President Federal Health Policy Strategies, former Counselor to the Secretary of the U.S. Department of Health & Human Services and Deputy Staff Director of the Ways and Means Health Subcommittee in the U.S House of Representatives
- [Ryann Hill](https://www.fah.org/about-fah/fah-staff/ryann-hill/), Vice President for Government Relations, Federation of American Hospitals

**Case Rubric**

- [Judges' Rubric](/materials/HPAM_7660_Case_Rubric.pdf)